// Generated by https://quicktype.io

export interface CaptureResponse {
  Status:                number;
  ReasonCode:            number;
  ReasonMessage:         string;
  ProviderReturnCode:    string;
  ProviderReturnMessage: string;
  ReturnCode:            string;
  ReturnMessage:         string;
  Tid:                   string;
  ProofOfSale:           string;
  AuthorizationCode:     string;
  Links:                 Link[];
}

export interface Link {
  Method: string;
  Rel:    string;
  Href:   string;
}
